import Head from 'next/head'

import HeaderStan from './components/header'
import Main from './components/main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ondřej Klekner - Party stany</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet"></link>
      </Head>

      <main>
        <HeaderStan/>
        <div className='px-72 h-screen bg-gray-100 shadow-2xl'>
          <Main/>
          
        </div>
       </main>
    </div>
  )
}
